const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const seedIngredients = async () => {
  const ingredients = [
    {
      name: 'All-purpose flour',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: 'cup',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '1 cup all-purpose flour',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 0,
    },
    {
      name: 'White sugar',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: 'tablespoon',
      unitOfMeasureID: 'tablespoon',
      isGroupHeader: false,
      input: '1 tablespoon white sugar',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 1,
    },
    {
      name: 'Baking powder',
      quantity: 2,
      quantity2: null,
      unitOfMeasure: 'teaspoons',
      unitOfMeasureID: 'teaspoon',
      isGroupHeader: false,
      input: '2 teaspoons baking powder',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 2,
    },
    {
      name: 'Salt',
      quantity: 0.25,
      quantity2: null,
      unitOfMeasure: 'teaspoon',
      unitOfMeasureID: 'teaspoon',
      isGroupHeader: false,
      input: '0.25 teaspoon salt',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 3,
    },
    {
      name: 'Egg, beaten',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '1 egg, beaten',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 4,
    },
    {
      name: 'Milk',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: 'cup',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '1 cup milk',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 5,
    },
    {
      name: 'Vegetable oil',
      quantity: 2,
      quantity2: null,
      unitOfMeasure: 'tablespoons',
      unitOfMeasureID: 'tablespoon',
      isGroupHeader: false,
      input: '2 tablespoons vegetable oil',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 6,
    },
    {
      name: 'Ripe bananas, mashed',
      quantity: 2,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '2 ripe bananas, mashed',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 7,
    },
    {
      name: 'Chocolate chips',
      quantity: null,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: 'Chocolate chips',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 0,
    },
    {
      name: 'Skinless, boneless chicken breast halves - cubed',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: 'pound',
      unitOfMeasureID: 'pound',
      isGroupHeader: false,
      input: '1 pound skinless, boneless chicken breast halves - cubed',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 0,
    },
    {
      name: 'Sliced carrots',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: 'cup',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '1 cup sliced carrots',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 1,
    },
    {
      name: 'Frozen green peas',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: 'cup',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '1 cup frozen green peas',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 2,
    },
    {
      name: 'Sliced celery',
      quantity: 0.5,
      quantity2: null,
      unitOfMeasure: 'cup',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '0.5 cup sliced celery',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 3,
    },
    {
      name: '1/3 cup butter',
      quantity: 1 / 3,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '1/3 cup butter',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 4,
    },
    {
      name: '1/3 cup chopped onion',
      quantity: 1 / 3,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '1/3 cup chopped onion',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 5,
    },
    {
      name: 'Celery seed',
      quantity: 0.25,
      quantity2: null,
      unitOfMeasure: 'teaspoon',
      unitOfMeasureID: 'teaspoon',
      isGroupHeader: false,
      input: '0.25 teaspoon celery seed',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 9,
    },
    {
      name: 'Chicken broth',
      quantity: 1.75,
      quantity2: null,
      unitOfMeasure: 'cups',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '1.75 cups chicken broth',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 10,
    },
    {
      name: '2/3 cup milk',
      quantity: 0.667,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '2/3 cup milk',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 11,
    },
    {
      name: '(9 inch) unbaked pie crusts',
      quantity: 2,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '2 (9 inch) unbaked pie crusts',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 12,
    },
    {
      name: 'Butter',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: 'tablespoon',
      unitOfMeasureID: 'tablespoon',
      isGroupHeader: false,
      input: '1 tablespoon butter',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 0,
    },
    {
      name: 'Chopped onion',
      quantity: 0.5,
      quantity2: null,
      unitOfMeasure: 'cup',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '0.5 cup chopped onion',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 1,
    },
    {
      name: 'Chopped celery',
      quantity: 0.5,
      quantity2: null,
      unitOfMeasure: 'cup',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '0.5 cup chopped celery',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 2,
    },
    {
      name: '(14.5 ounce) cans chicken broth',
      quantity: 4,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '4 (14.5 ounce) cans chicken broth',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 3,
    },
    {
      name: '(14.5 ounce) can vegetable broth',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '1 (14.5 ounce) can vegetable broth',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 4,
    },
    {
      name: 'Chopped cooked chicken breast',
      quantity: 0.5,
      quantity2: null,
      unitOfMeasure: 'pound',
      unitOfMeasureID: 'pound',
      isGroupHeader: false,
      input: '0.5 pound chopped cooked chicken breast',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 5,
    },
    {
      name: 'Egg noodles',
      quantity: 1.5,
      quantity2: null,
      unitOfMeasure: 'cups',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '1.5 cups egg noodles',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 6,
    },
    {
      name: 'Sliced carrots',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: 'cup',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '1 cup sliced carrots',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 7,
    },
    {
      name: 'Dried basil',
      quantity: 0.5,
      quantity2: null,
      unitOfMeasure: 'teaspoon',
      unitOfMeasureID: 'teaspoon',
      isGroupHeader: false,
      input: '0.5 teaspoon dried basil',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 8,
    },
    {
      name: 'Dried oregano',
      quantity: 0.5,
      quantity2: null,
      unitOfMeasure: 'teaspoon',
      unitOfMeasureID: 'teaspoon',
      isGroupHeader: false,
      input: '0.5 teaspoon dried oregano',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 9,
    },
    {
      name: 'Apples',
      quantity: null,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: 'Apples',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 0,
    },
    {
      name: 'Cinnamon',
      quantity: null,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: 'Cinnamon',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 3,
    },
    {
      name: '2/3 cup soy sauce',
      quantity: 0.667,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '2/3 cup soy sauce',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 0,
    },
    {
      name: 'Red pepper flakes, or to taste',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: 'pinch',
      unitOfMeasureID: 'pinch',
      isGroupHeader: false,
      input: '1 pinch red pepper flakes, or to taste',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 3,
    },
    {
      name: 'Cornstarch',
      quantity: 2,
      quantity2: null,
      unitOfMeasure: 'tablespoons',
      unitOfMeasureID: 'tablespoon',
      isGroupHeader: false,
      input: '2 tablespoons cornstarch',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 5,
    },
    {
      name: 'Vegetable oil, or to taste',
      quantity: 2,
      quantity2: null,
      unitOfMeasure: 'teaspoons',
      unitOfMeasureID: 'teaspoon',
      isGroupHeader: false,
      input: '2 teaspoons vegetable oil, or to taste',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 6,
    },
    {
      name: 'Skinless, boneless chicken breast halves, cut into chunks',
      quantity: 3,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '3 skinless, boneless chicken breast halves, cut into chunks',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 7,
    },
    {
      name: 'Onion, sliced',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '1 onion, sliced',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 8,
    },
    {
      name: 'Broccoli florets',
      quantity: 3,
      quantity2: null,
      unitOfMeasure: 'cups',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '3 cups broccoli florets',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 9,
    },
    {
      name: '2/3 cup soy sauce',
      quantity: 0.667,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '2/3 cup soy sauce',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 0,
    },
    {
      name: 'Ground ginger',
      quantity: 0.5,
      quantity2: null,
      unitOfMeasure: 'teaspoon',
      unitOfMeasureID: 'teaspoon',
      isGroupHeader: false,
      input: '0.5 teaspoon ground ginger',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 2,
    },
    {
      name: 'Water',
      quantity: 2,
      quantity2: null,
      unitOfMeasure: 'tablespoons',
      unitOfMeasureID: 'tablespoon',
      isGroupHeader: false,
      input: '2 tablespoons water',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 4,
    },
    {
      name: 'Cornstarch',
      quantity: 2,
      quantity2: null,
      unitOfMeasure: 'tablespoons',
      unitOfMeasureID: 'tablespoon',
      isGroupHeader: false,
      input: '2 tablespoons cornstarch',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 5,
    },
    {
      name: 'Vegetable oil, or to taste',
      quantity: 2,
      quantity2: null,
      unitOfMeasure: 'teaspoons',
      unitOfMeasureID: 'teaspoon',
      isGroupHeader: false,
      input: '2 teaspoons vegetable oil, or to taste',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 6,
    },
    {
      name: 'Skinless, boneless chicken breast halves, cut into chunks',
      quantity: 3,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '3 skinless, boneless chicken breast halves, cut into chunks',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 7,
    },
    {
      name: 'Onion, sliced',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '1 onion, sliced',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 8,
    },
    {
      name: 'Broccoli florets',
      quantity: 3,
      quantity2: null,
      unitOfMeasure: 'cups',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '3 cups broccoli florets',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 9,
    },
    {
      name: 'Dried oregano',
      quantity: 0.5,
      quantity2: null,
      unitOfMeasure: 'teaspoon',
      unitOfMeasureID: 'teaspoon',
      isGroupHeader: false,
      input: '0.5 teaspoon dried oregano',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 3,
    },
    {
      name: 'Skinless, boneless chicken breast halves - pounded 1/4 inch thick',
      quantity: 4,
      quantity2: null,
      unitOfMeasure: 'medium',
      unitOfMeasureID: 'medium',
      isGroupHeader: false,
      input:
        '4 medium skinless, boneless chicken breast halves - pounded 1/4 inch thick',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 4,
    },
    {
      name: 'Butter',
      quantity: 4,
      quantity2: null,
      unitOfMeasure: 'tablespoons',
      unitOfMeasureID: 'tablespoon',
      isGroupHeader: false,
      input: '4 tablespoons butter',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 5,
    },
    {
      name: 'Olive oil',
      quantity: 4,
      quantity2: null,
      unitOfMeasure: 'tablespoons',
      unitOfMeasureID: 'tablespoon',
      isGroupHeader: false,
      input: '4 tablespoons olive oil',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 6,
    },
    {
      name: 'Sliced mushrooms',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: 'cup',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '1 cup sliced mushrooms',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 7,
    },
    {
      name: 'Marsala wine',
      quantity: 0.5,
      quantity2: null,
      unitOfMeasure: 'cup',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '0.5 cup Marsala wine',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 8,
    },
    {
      name: 'Cooking sherry',
      quantity: 0.25,
      quantity2: null,
      unitOfMeasure: 'cup',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '0.25 cup cooking sherry',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 9,
    },
    {
      name: 'Eggs',
      quantity: 2,
      quantity2: null,
      unitOfMeasure: 'large',
      unitOfMeasureID: 'large',
      isGroupHeader: false,
      input: '2 large eggs',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 0,
    },
    {
      name: 'Italian seasoned bread crumbs',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: 'cup',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '1 cup Italian seasoned bread crumbs',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 3,
    },
    {
      name: 'Skinless, boneless chicken breast halves, thinly sliced',
      quantity: 2,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '2 skinless, boneless chicken breast halves, thinly sliced',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 4,
    },
    {
      name: 'Vegetable oil for frying',
      quantity: 0.25,
      quantity2: null,
      unitOfMeasure: 'cup',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '0.25 cup vegetable oil for frying',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 5,
    },
    {
      name: 'Lemon, cut into wedges',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '1 lemon, cut into wedges',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 6,
    },
    {
      name: 'Tri-colored spiral pasta',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: 'pound',
      unitOfMeasureID: 'pound',
      isGroupHeader: false,
      input: '1 pound tri-colored spiral pasta',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 0,
    },
    {
      name: '(16 ounce) bottle Italian-style salad dressing',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '1 (16 ounce) bottle Italian-style salad dressing',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 1,
    },
    {
      name: 'Salad seasoning mix',
      quantity: 6,
      quantity2: null,
      unitOfMeasure: 'tablespoons',
      unitOfMeasureID: 'tablespoon',
      isGroupHeader: false,
      input: '6 tablespoons salad seasoning mix',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 2,
    },
    {
      name: 'Cherry tomatoes, diced',
      quantity: 2,
      quantity2: null,
      unitOfMeasure: 'cups',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '2 cups cherry tomatoes, diced',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 3,
    },
    {
      name: 'Green bell pepper, chopped',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '1 green bell pepper, chopped',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 4,
    },
    {
      name: 'Red bell pepper, diced',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '1 red bell pepper, diced',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 5,
    },
    {
      name: 'Yellow bell pepper, chopped',
      quantity: 0.5,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '0.5 yellow bell pepper, chopped',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 6,
    },
    {
      name: '(2.25 ounce) can black olives, chopped',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '1 (2.25 ounce) can black olives, chopped',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 7,
    },
    {
      name: 'Small red new potatoes, halved',
      quantity: 3,
      quantity2: null,
      unitOfMeasure: 'pounds',
      unitOfMeasureID: 'pound',
      isGroupHeader: false,
      input: '3 pounds small red new potatoes, halved',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 0,
    },
    {
      name: 'Olive oil',
      quantity: 0.25,
      quantity2: null,
      unitOfMeasure: 'cup',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '0.25 cup olive oil',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 1,
    },
    {
      name: '2/3 cup fresh orange juice',
      quantity: 0.667,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '2/3 cup fresh orange juice',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 0,
    },
    {
      name: '1/3 cup fresh lemon juice',
      quantity: 1 / 3,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '1/3 cup fresh lemon juice',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 1,
    },
    {
      name: 'Brown sugar',
      quantity: 1 / 3,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '1/3 cup packed brown sugar',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 2,
    },
    {
      name: 'Grated orange zest',
      quantity: 0.5,
      quantity2: null,
      unitOfMeasure: 'teaspoon',
      unitOfMeasureID: 'teaspoon',
      isGroupHeader: false,
      input: '0.5 teaspoon grated orange zest',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 3,
    },
    {
      name: 'Grated lemon zest',
      quantity: 0.5,
      quantity2: null,
      unitOfMeasure: 'teaspoon',
      unitOfMeasureID: 'teaspoon',
      isGroupHeader: false,
      input: '0.5 teaspoon grated lemon zest',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 4,
    },
    {
      name: 'Vanilla extract',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: 'teaspoon',
      unitOfMeasureID: 'teaspoon',
      isGroupHeader: false,
      input: '1 teaspoon vanilla extract',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 5,
    },
    {
      name: 'Cubed fresh pineapple',
      quantity: 2,
      quantity2: null,
      unitOfMeasure: 'cups',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '2 cups cubed fresh pineapple',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 6,
    },
    {
      name: 'Strawberries, hulled and sliced',
      quantity: 2,
      quantity2: null,
      unitOfMeasure: 'cups',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '2 cups strawberries, hulled and sliced',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 7,
    },
    {
      name: 'Kiwi fruit, peeled and sliced',
      quantity: 3,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '3 kiwi fruit, peeled and sliced',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 8,
    },
    {
      name: 'Bananas, sliced',
      quantity: 3,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '3 bananas, sliced',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 9,
    },
    {
      name: 'Oranges, peeled and sectioned',
      quantity: 2,
      quantity2: null,
      unitOfMeasure: '',
      unitOfMeasureID: '',
      isGroupHeader: false,
      input: '2 oranges, peeled and sectioned',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 10,
    },
    {
      name: 'Seedless grapes',
      quantity: 1,
      quantity2: null,
      unitOfMeasure: 'cup',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '1 cup seedless grapes',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 11,
    },
    {
      name: 'Blueberries',
      quantity: 2,
      quantity2: null,
      unitOfMeasure: 'cups',
      unitOfMeasureID: 'cup',
      isGroupHeader: false,
      input: '2 cups blueberries',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 12,
    },
    {
      name: 'Russet potatoes, shredded',
      quantity: 2,
      quantity2: null,
      unitOfMeasure: 'medium',
      unitOfMeasureID: 'medium',
      isGroupHeader: false,
      input: '2 medium russet potatoes, shredded',
      createdAt: new Date(),
      updatedAt: new Date(),
      order: 0,
    },
  ];

  for (const ingredient of ingredients) {
    await prisma.ingredient.create({
      data: ingredient,
    });
  }
};

module.exports = { seedIngredients };
