const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const seedCuisines = async () => {
  const cuisines = [
    { name: 'African' },
    { name: 'American' },
    { name: 'Australian' },
    { name: 'Belgian' },
    { name: 'Beninese' },
    { name: 'Brazilian' },
    { name: 'British' },
    { name: 'Bulgarian' },
    { name: 'Burkinabe' },
    { name: 'Burundian' },
    { name: 'Cajun' },
    { name: 'Cameroonian' },
    { name: 'Canadian' },
    { name: 'Caribbean' },
    { name: 'Central African' },
    { name: 'Chadian' },
    { name: 'Chinese' },
    { name: 'Comoran' },
    { name: 'Congolese' },
    { name: 'Cypriot' },
    { name: 'Czech' },
    { name: 'Danish' },
    { name: 'Djiboutian' },
    { name: 'Dutch' },
    { name: 'Eastern European' },
    { name: 'Egyptian' },
    { name: 'Equatorial Guinean' },
    { name: 'Eritrean' },
    { name: 'Ethiopian' },
    { name: 'European' },
    { name: 'Finnish' },
    { name: 'French' },
    { name: 'Gabonese' },
    { name: 'German' },
    { name: 'Ghanaian' },
    { name: 'Greek' },
    { name: 'Guinean' },
    { name: 'Hungarian' },
    { name: 'Indian' },
    { name: 'Indonesian' },
    { name: 'Irish' },
    { name: 'Israeli' },
    { name: 'Italian' },
    { name: 'Ivorian' },
    { name: 'Japanese' },
    { name: 'Jewish' },
    { name: 'Kenyan' },
    { name: 'Korean' },
    { name: 'Latin American' },
    { name: 'Lebanese' },
    { name: 'Liberian' },
    { name: 'Libyan' },
    { name: 'Malian' },
    { name: 'Malagasy' },
    { name: 'Mauritanian' },
    { name: 'Mauritian' },
    { name: 'Mediterranean' },
    { name: 'Mexican' },
    { name: 'Middle Eastern' },
    { name: 'Mozambican' },
    { name: 'Namibian' },
    { name: 'Nigerian' },
    { name: 'Nigerien' },
    { name: 'Nordic' },
    { name: 'Norwegian' },
    { name: 'Polish' },
    { name: 'Portuguese' },
    { name: 'Romanian' },
    { name: 'Russian' },
    { name: 'Rwandan' },
    { name: 'Sao Tomean' },
    { name: 'Scottish' },
    { name: 'Senegalese' },
    { name: 'Seychellois' },
    { name: 'Sierra Leonean' },
    { name: 'Slovak' },
    { name: 'Somali' },
    { name: 'South African' },
    { name: 'Southern' },
    { name: 'Spanish' },
    { name: 'Sudanese' },
    { name: 'Swedish' },
    { name: 'Swiss' },
    { name: 'Tanzanian' },
    { name: 'Thai' },
    { name: 'Togolese' },
    { name: 'Tunisian' },
    { name: 'Turkish' },
    { name: 'Ugandan' },
    { name: 'Vietnamese' },
    { name: 'Welsh' },
    { name: 'Zambian' },
    { name: 'Zimbabwean' },
  ];

  for (const cuisine of cuisines) {
    await prisma.cuisine.create({
      data: cuisine,
    });
  }
};

module.exports = { seedCuisines };
